# mathematical operation using numpy

In [1]:
import numpy as np

In [13]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.arange(1,10).reshape(3,3)

print(array1)

print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
array1 + array2    #addition of two matrix

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
np.add(array1 ,array2)     # addition using add method 

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [17]:
array1 - array2           #substraction of two matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
array1 / array2           #divide of two matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.divide(array1 ,array2)  #divide 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
array1 * array2             #multiplication of two matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [22]:
np.multiply(array1 ,array2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [23]:
array1 @ array2           #1st row 1st column * multi

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [24]:
array1.max()      #max value

9

In [25]:
array.argmax()      #position of highter element in array find index 

8

In [27]:
array1.max(axis = 0)     # 0 means column 

array([7, 8, 9])

In [28]:
array1.max(axis = 1)     # 1 means rows 

array([3, 6, 9])

In [29]:
array1.min()

1

In [30]:
array.argmin()

0

In [31]:
array1.min(axis = 0)

array([1, 2, 3])

In [32]:
array1.min(axis = 1)

array([1, 4, 7])

In [33]:
#sum of array element 
np.sum(array1)

45

In [36]:
#sum of each column

np.sum(array1 , axis = 0)

array([12, 15, 18])

In [41]:
#sum of each row

np.sum(array1,axis =1)

array([ 6, 15, 24])

In [42]:
np.mean(array1)

5.0

In [43]:
np.exp(array1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [44]:
np.log(array1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [45]:
np.sqrt(array1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])