In [1]:
import numpy as np


In [2]:
x=np.array([1,2,3,4])

In [3]:
x


array([1, 2, 3, 4])

In [4]:
type(x)


numpy.ndarray

In [5]:
x.ndim  #dimension 

1

In [6]:
x=np.array([[1,2,3,4],[56,78,45,34]])

In [7]:
x

array([[ 1,  2,  3,  4],
       [56, 78, 45, 34]])

In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

2

In [10]:
x.size

8

In [11]:
x.shape # 2 rows 4 column

(2, 4)

In [12]:
x.dtype     #check data type

dtype('int32')

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
y = np.ones((3,4))

In [16]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones((3,4),dtype = int )  # to convert int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.empty((2,2))

array([[7.93363185e+069, 1.66460623e-312],
       [3.12140488e-308, 4.55907840e-239]])