# numpy function

In [1]:
import numpy as np

# arange()

In [2]:
#np.arange(start value,end value ,steps)

x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
even_array = np.arange(1,15,2)
even_array

array([ 1,  3,  5,  7,  9, 11, 13])

# linspace()

In [10]:
np.linspace(1,10,4)         #give sem difference 

array([ 1.,  4.,  7., 10.])

# reshape()

In [15]:
array_2d =x.reshape(2,7)
array_2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

# ravel() convert multi dimension arrry to one dimension

In [16]:
array_2d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# flatten()

In [18]:
array_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# transpose()
#convert (2,6 ) to (6,2) 

In [21]:
array_2d.transpose()

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])