# Random sampling with numpy

In [2]:
import numpy as np
import random

In [15]:
x = np.random.random(1)   #random.ramdom its give value between 0 to 1 always

In [14]:
x

array([0.28542817])

In [17]:
np.random.random((3,3))         #3 rows 3 columns 

array([[0.64613047, 0.2325827 , 0.82635793],
       [0.24334601, 0.65974963, 0.81303537],
       [0.68043619, 0.29819406, 0.71325221]])

In [24]:
np.random.randint(1,4)     # single value (1,4) range

3

In [26]:
np.random.randint(1,10 , (4,4))

array([[1, 7, 1, 4],
       [9, 7, 5, 4],
       [3, 1, 1, 7],
       [7, 5, 9, 5]])

In [27]:
np.random.seed(10)
np.random.randint(1,10 , (4,4))

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1],
       [5, 7, 9, 2]])

In [28]:
np.random.seed(10)
np.random.randint(1,10 , (4,4))

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1],
       [5, 7, 9, 2]])

In [29]:
np.random.rand(3,3)

array([[0.72175532, 0.29187607, 0.91777412],
       [0.71457578, 0.54254437, 0.14217005],
       [0.37334076, 0.67413362, 0.44183317]])

In [31]:
np.random.randn(3,3)     #randn gives negative nd positive values

array([[-0.26854813, -0.66630197, -0.34401183],
       [ 0.80705192,  2.14180538, -0.49561818],
       [ 0.52563742, -0.38964647,  0.9372965 ]])

In [41]:
x = [1,2,3,4]
np.random.choice(x)       


3

In [42]:
np.random.permutation(x)   

array([2, 4, 3, 1])